#!/usr/bin/env node
/**
 * `npm run sync` — rebase local work onto origin/main, resolving data/ conflicts
 * automatically.
 *
 * Why this exists: the update workflow commits regenerated data/feed.json and
 * data/status.json on every run (12 a day), so a local clone falls behind within
 * hours and any `git push` is rejected. The rebase then conflicts on those two
 * files every single time.
 *
 * The resolution is always the same, because data/ is *generated output*: keep
 * whichever copy the local commit produced and let the next scheduled run
 * regenerate from live sources anyway. There is never anything to merge by hand.
 *
 * Only data/*.json is auto-resolved. A conflict in any other file is a real
 * conflict and stops the script for you to look at.
 */

import { execFileSync } from 'node:child_process';

const GENERATED = ['data/feed.json', 'data/status.json'];

function git(args, { allowFail = false } = {}) {
  try {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  } catch (error) {
    if (allowFail) return null;
    console.error(`git ${args.join(' ')} failed:\n${error.stderr || error.message}`);
    process.exit(1);
  }
}

const dirty = git(['status', '--porcelain']).split('\n').filter((l) => l && !l.startsWith('??'));
if (dirty.length) {
  console.error('You have uncommitted changes. Commit or stash them first:\n');
  for (const line of dirty) console.error(`  ${line}`);
  process.exit(1);
}

console.log('Fetching origin…');
git(['fetch', 'origin']);

const behind = git(['rev-list', '--count', 'HEAD..origin/main']);
const ahead = git(['rev-list', '--count', 'origin/main..HEAD']);
console.log(`  ${ahead} local commit(s) to push, ${behind} remote commit(s) to absorb.`);

if (behind === '0') {
  console.log('Already up to date with origin/main — nothing to rebase.');
  process.exit(0);
}

console.log('Rebasing onto origin/main…');
const rebase = git(['rebase', 'origin/main'], { allowFail: true });

if (rebase !== null) {
  console.log('Clean rebase, no conflicts.');
  process.exit(0);
}

// Conflicted. Auto-resolve only the generated files.
const conflicted = git(['diff', '--name-only', '--diff-filter=U']).split('\n').filter(Boolean);
const unexpected = conflicted.filter((f) => !GENERATED.includes(f));

if (unexpected.length) {
  console.error('\nConflicts in files that are NOT generated output — resolve these yourself:\n');
  for (const file of unexpected) console.error(`  ${file}`);
  console.error('\nThen: git add <files> && git rebase --continue');
  console.error('Or abandon the attempt with: git rebase --abort');
  process.exit(1);
}

console.log(`Auto-resolving generated files: ${conflicted.join(', ')}`);
// REBASE_HEAD is the commit currently being replayed, i.e. the local work.
git(['checkout', 'REBASE_HEAD', '--', ...conflicted]);
git(['add', ...conflicted]);

const continued = git(['-c', 'core.editor=true', 'rebase', '--continue'], { allowFail: true });
if (continued === null) {
  console.error('\nRebase still stuck after auto-resolving. Inspect with: git status');
  process.exit(1);
}

console.log('\nRebased cleanly. Now: git push origin main');
console.log('(data/ will be regenerated by the next scheduled run regardless.)');
